version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run: php --version

      # composer require
      - run: composer require --dev phpunit/phpunit ^5
      - run: composer require --dev php-coveralls/php-coveralls ^1
      - run: composer require --dev atoum/atoum ^3

      # composer cache
      - restore_cache:
          keys:
          # "composer.json" can be used if "composer.json"
          # is not committed to the repository.
          - composer-v1-{{ checksum "composer.lock" }}
          # fallback to using the latest cache if no exact match is found
          - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # tests
      - run: php vendor/bin/phpunit Tests/phpunit -c phpunit.xml.dist
      - run: php vendor/bin/atoum -d Tests/atoum

# Orchestrate our job run sequence
workflows:
  workflow:
    jobs:
      - test



machine:
  php:
    version: 5.4.10

## Customize dependencies
dependencies:
  override:
    - mkdir -p build/logs
    - composer install --no-interaction --optimize-autoloader
    - sed -i 's/^;//' ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini

## Customize test commands
test:
  override:
    - php vendor/bin/phpunit Tests/phpunit -c phpunit.xml.dist
    - php vendor/bin/atoum -d Tests/atoum
