name: PHP Composer

on:
  push:
    branches: [ "master", "1.x" ]
  pull_request:
    branches: [ "master", "1.x" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install phpunit dev
      run: composer require --dev phpunit/phpunit ^5

    - name: Install php-coveralls dev
      run: composer require --dev php-coveralls/php-coveralls ^1

    - name: Install atoum dev
      run: composer require --dev atoum/atoum ^3

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run phpunit test
      run: php vendor/bin/phpunit Tests/phpunit -c phpunit.xml.dist

    - name: Run atoum test
      run: php vendor/bin/atoum -d Tests/atoum

    - name: npm install, make test-coverage
      run: |
        npm install
        make test-coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4

    - name: Coveralls
      uses: coverallsapp/github-action@v2

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
